controllers/AccountController.php
<?php

namespace app\controllers;

use app\models\Account;
use Yii;
use app\models\Candidate;
use yii\filters\AccessControl;
use yii\web\Controller;

/**
 * Class AccountController
 * @package app\controllers
 */
class AccountController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionList()
    {
        $request = Yii::$app->getRequest();

        /** @var Yii\db\ActiveQuery $accounts */
        $accounts = Account::find();

        if (null !== ($term = $request->get('query'))) {
            $accounts->andWhere(['like', 'name', $term]);
        }

        $accounts = $accounts->all();

        if (Yii::$app->getRequest()->getIsAjax()) {
            Yii::$app->response->format = 'json';

            return [
                'success' => true,
                'data' => $accounts,
            ];
        }

        return $this->render($this->action->id, [
            'models' => $accounts,
        ]);
    }

}

controllers/InterviewController.php
<?php

namespace app\controllers;

use app\forms\interview\Complete as InterviewComplete;
use app\forms\SendNotification;
use Yii;
use app\models\InterviewParticipant;
use app\forms\Interview;
use app\models\Candidate;
use app\models\Feedback;
use app\models\User;
use Eluceo\iCal\Component\Calendar as iCalCalendar;
use Eluceo\iCal\Component\Event as iCalEvent;
use yii\base\Event;
use yii\filters\AccessControl;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\Controller;
use app\models\Interview as InterviewModel;

/**
 * Class InterviewController
 * @package app\controllers
 */
class InterviewController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['feedback'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
        ];
    }

    public function actionCreate()
    {
        $request = Yii::$app->getRequest();
        $interviewForm = new Interview();

        if ($interviewId = (int)$request->get('interview_id')) {
            $interviewModel = InterviewModel::findOne($interviewId);
        } else {
            $interviewModel = new InterviewModel();
        }

        if ($request->getIsPost() && $interviewForm->load($request->post())) {
            /** @var \app\helpers\AjaxMessage $ajaxMessage */
            $ajaxMessage = Yii::$app->ajaxMessage;

            if ($interviewForm->validate()) {
                if ($interviewModel->getIsNewRecord() && $interviewForm->interview_id) {
                    $interviewModel = InterviewModel::findOne($interviewForm->interview_id);
                }
                $interviewModel->setAttributes($interviewForm->getAttributes());

                $transaction = Yii::$app->getDb()->beginTransaction();

                try {
                    if (false === $interviewModel->save(false)) {
                        throw new \Exception('Cannot update interview');
                    }

                    $candidate = Candidate::findOne($interviewForm->candidate_id);

                    // remove all related
                    InterviewParticipant::deleteAll(['interview_id' => $interviewModel->id]);

                    $participants = explode(',', $interviewForm->participants);
                    $users = User::find()->where(['full_name' => $participants])->all();

                    // save into history
//                    Yii::$app->trigger('history.create', new Event(['sender' => $candidate, 'data' => ['asd', '123']]));

                    /** @var User $userModel */
                    foreach ($users as $userModel) {
                        $interviewParticipant = new InterviewParticipant();

                        $interviewParticipant->user_id = $userModel->id;
                        $interviewParticipant->interview_id = $interviewModel->id;
                        $interviewParticipant->candidate_id = $candidate->id;

                        if (false === $interviewParticipant->save()) {
                            throw new \Exception('Cannot update interview participant');
                        }
                    }

                    if ($interviewForm->send_invitation) {
                        $subject = [$candidate->getFullName(), $interviewForm->vacancy, $interviewForm->account];
                        $subject = Yii::t('app', 'Interview') . ': ' . join(' > ', $subject);

                        /** @var User $currentUser */
                        $currentUser = Yii::$app->getUser()->getIdentity();

                        $mailer = Yii::$app->mailer
                            ->compose('interview/create', [
                                'comment' => $interviewForm->comment,
                                'isAttachCv' => $interviewForm->attach_cv,
                                'appointmentAt' => $interviewForm->appointment_at,
                            ])
                            ->setFrom([$currentUser->email => $currentUser->full_name])
                            ->setSubject($subject);

                        if ($interviewForm->attach_cv) {
                            /** @var \app\models\Cv $cv */
                            foreach (Candidate::findOne($interviewForm->candidate_id)->getCvs()->all() as $cv) {
                                $mailer->attach($cv->getFullPath());
                            }
                        }

                        //region iCal reminder
                        $utcTz = new \DateTimeZone('UTC');
                        $dateInterval = new \DateInterval('PT1H');

                        $appointmentStart = new \DateTime($interviewForm->appointment_at);
                        $appointmentStart->setTimezone($utcTz);

                        $appointmentEnd = new \DateTime();
                        $appointmentEnd->setTimestamp($appointmentStart->getTimestamp());
                        $appointmentEnd->setTimezone($utcTz);
                        $appointmentEnd->add($dateInterval);

                        $vEvent = (new iCalEvent(sha1($interviewModel->id) . '@recruiting.brightgrove.com'))
                            ->setDtStart($appointmentStart)
                            ->setDtEnd($appointmentEnd)
                            ->setDuration($dateInterval)
                            ->setLocation('Kharkiv, Brightgrove Ltd, Kooperativnaya str, 1a, Meeting room')
                            ->setStatus(iCalEvent::STATUS_CONFIRMED)
                            ->setSequence(0)
                            ->setUseUtc(true)
                            ->setOrganizer("CN={$currentUser->full_name}:mailto:{$currentUser->email}")
                            ->setSummary($subject);

                        if ($interviewForm->comment) {
                            $vEvent->setDescription($interviewForm->comment);
                        }

                        $vCalendar = new iCalCalendar('Recruiting Reminders');
                        $vCalendar->addComponent($vEvent);
                        $vCalendar->setMethod(iCalCalendar::METHOD_REQUEST);
                        $iCalContent = $vCalendar->render();

                        $attendee = '';
                        $usersMail = [];
                        /** @var User $user */
                        foreach ($users as $user) {
                            $attendee .= sprintf(
                                '%sATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=%s;X-NUM-GUESTS=0:mailto:%s',
                                "\r\n",
                                $user->full_name,
                                $user->email
                            );
                            $usersMail[$user->email] = $user->full_name;
                        }
                        $mailer->setTo($usersMail);
                        unset($usersMail);

                        $iCalContent = preg_replace('/\s+END:VEVENT/', $attendee . '$0', $iCalContent);
                        unset($attendee);

                        $mailer->attachContent($iCalContent, [
                            'fileName' => 'invite.ics',
                            'contentType' => 'text/calendar; charset=utf-8; method=REQUEST',
                        ]);

                        $mailer->send();
                    }

                    $ajaxMessage->addSuccessMessage(sprintf('Interview for %s has been created', $candidate->getFullName()));
                    Yii::$app->response->format = 'json';

                    $transaction->commit();

                    return [
                        'success' => true,
                        'messages' => $ajaxMessage->getMessages(),
                    ];
                } catch (\Exception $e) {
                    $ajaxMessage->addExceptionError($e);
                    $transaction->rollBack();
                }
            }
        } elseif ($interviewId) {
            $interviewForm->setAttributes($interviewModel->getAttributes());
            /** @var InterviewParticipant $interviewParticipant */
            foreach ($interviewModel->getInterviewParticipants()->all() as $interviewParticipant) {
                $interviewForm->candidate_id = $interviewParticipant->candidate_id;
                $interviewForm->participants .= $interviewParticipant->getUser()->one()->getFullName() . ',';
            }
            $interviewForm->participants = rtrim($interviewForm->participants, ',');
            $interviewForm->vacancy = $interviewModel->getVacancy()->one()->name;
            $interviewForm->account = $interviewModel->getAccount()->one()->name;
            $interviewForm->interview_id = $interviewModel->id;

        } elseif ($candidateId = (int)$request->get('candidate_id')) {
            $interviewForm->candidate_id = $candidateId;
            $interviewForm->participants = $this->getRequiredParticipants($candidateId);
        }

        return $this->renderAjax($this->action->id, [
            'model' => $interviewForm,
        ]);
    }

    public function actionFeedback($id)
    {
        $model = new Feedback();
        $request = Yii::$app->getRequest();

        if ($model->load($request->post())) {
            $model->interview_id = $id;

            if ($model->save()) {
                return $this->render('feedback/success');
            }
        }

        return $this->render($this->action->id, [
            'model' => $model,
        ]);
    }

//    public function actionInterviewComplete()
//    {
//        $request = Yii::$app->getRequest();
//        $form = new InterviewComplete();
//

controllers/VacancyController.php
<?php

namespace app\controllers;

use app\models\Vacancy;
use Yii;
use app\models\Candidate;
use yii\filters\AccessControl;
use yii\web\Controller;

/**
 * Class VacancyController
 * @package app\controllers
 */
class VacancyController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionList()
    {
        $request = Yii::$app->getRequest();

        /** @var Yii\db\ActiveQuery $accounts */
        $accounts = Vacancy::find();

        if (null !== ($term = $request->get('query'))) {
            $accounts->andWhere(['like', 'name', $term]);
        }

        $accounts = $accounts->all();

        if (Yii::$app->getRequest()->getIsAjax()) {
            Yii::$app->response->format = 'json';

            return [
                'success' => true,
                'data' => $accounts,
            ];
        }

        return $this->render($this->action->id, [
            'models' => $accounts,
        ]);
    }

}

views/interview/create.php
<?php
use kartik\widgets\ActiveForm;
use app\widgets\TypeAhead;
use dosamigos\typeahead\Bloodhound;
use yii\tagsinput\TagsInput;
use yii\helpers\Url;
use kartik\widgets\DateTimePicker;
use yii\helpers\Html;
use yii\web\JsExpression;

$accountEngine = new Bloodhound([
    'name' => 'accountEngine',
    'clientOptions' => [
        'datumTokenizer' => new JsExpression('Bloodhound.tokenizers.obj.whitespace(\'name\')'),
        'queryTokenizer' => new JsExpression('Bloodhound.tokenizers.whitespace'),
        'remote' => [
            'url' => Url::to(['/account/list', 'query' => 'QRY']),
            'wildcard' => 'QRY',
            'filter' => new JsExpression('function (list) {
                return $.map(list.data, function (account) {
                    return account;
                });
            }')
        ]
    ]
]);

$vacancyEngine = new Bloodhound([
    'name' => 'vacancyEngine',
    'clientOptions' => [
        'datumTokenizer' => new JsExpression('Bloodhound.tokenizers.obj.whitespace(\'name\')'),
        'queryTokenizer' => new JsExpression('Bloodhound.tokenizers.whitespace'),
        'remote' => [
            'url' => Url::to(['/vacancy/list', 'query' => 'QRY']),
            'wildcard' => 'QRY',
            'filter' => new JsExpression('function (list) {
                return $.map(list.data, function (account) {
                    return account;
                });
            }')
        ]
    ]
]);

/** @var app\models\Interview $model */
$form = ActiveForm::begin([
    'action' => Url::to('/interview/create'),
    'id' => $model->formName(),
    'enableClientValidation' => false,
    'options' => [
        'class' => 'clearfix',
    ]
]); ?>

<?= Html::activeHiddenInput($model, 'interview_id'); ?>
<?= Html::activeHiddenInput($model, 'vacancy_id'); ?>
<?= Html::activeHiddenInput($model, 'account_id'); ?>
<?= Html::activeHiddenInput($model, 'candidate_id'); ?>

<div class="row">
    <?= $form->field($model, 'account', ['options' => ['class' => 'form-group col-sm-6 col-md-6 col-lg-6']])->widget(TypeAhead::className(), [
        'options' => ['class' => 'form-control'],
        'engines' => [$accountEngine],
        'events' => [
            'selected' => new JsExpression('function (e, item) {
                $(\'#interview-form :hidden[name*="account_id"]\').val(item.id);
            }'),
        ],
        'clientOptions' => [
            'highlight' => true,
            'minLength' => 2,
        ],
        'dataSets' => [
            [
                'displayKey' => 'name',
                'valueKey' => 'id',
                'source' => $accountEngine->getAdapterScript(),
            ],
        ],
    ]); ?>

    <?= $form->field($model, 'vacancy', ['options' => ['class' => 'form-group col-sm-6 col-md-6 col-lg-6']])->widget(TypeAhead::className(), [
        'options' => ['class' => 'form-control'],
        'engines' => [$vacancyEngine],
        'events' => [
            'selected' => new JsExpression('function (e, item) {
                $(\'#interview-form :hidden[name*="vacancy_id"]\').val(item.id);
            }'),
        ],
        'clientOptions' => [
            'highlight' => true,
            'minLength' => 2,
        ],
        'dataSets' => [
            [
                'displayKey' => 'name',
                'valueKey' => 'name',
                'source' => $vacancyEngine->getAdapterScript(),
            ],
        ],
    ]); ?>
</div>

<?= $form->field($model, 'appointment_at')->widget(DateTimePicker::className(), [
    'type' => DateTimePicker::TYPE_COMPONENT_PREPEND,
    'pluginOptions' => [
        'daysOfWeekDisabled' => [0, 6],
        'todayHighlight' => true,
        'autoclose' => true,
        'format' => 'yyyy-mm-dd hh:ii',
    ],
]); ?>

<?= $form->field($model, 'participants')->widget(TagsInput::className(), [
    'clientOptions' => [
        'typeaheadjs' => [
            'displayKey' => 'full_name',
            'valueKey' => 'full_name',
            'source' => new JsExpression('(function () {
                var users = new Bloodhound({
                    datumTokenizer: Bloodhound.tokenizers.obj.whitespace(\'full_name\'),
                    queryTokenizer: Bloodhound.tokenizers.whitespace,
                    remote: {
                        url: \'/user/list?term=%QUERY\',
                        filter: function (list) {
                            return $.map(list.data, function (user) {
                                return user;
                            });
                        }
                    }
                });
                users.initialize();
                return users.ttAdapter();
            })()'),
        ],
    ]
]); ?>
<?= $form->field($model, 'comment')->textarea(); ?>

<div class="row">
    <div class="col-md-4"><?= Html::activeCheckbox($model, 'send_invitation', ['class' => 'interview-checker']); ?></div>
    <div class="col-md-8"><?= Html::activeCheckbox($model, 'attach_cv', ['class' => 'interview-attach-cv']); ?></div>
</div>

<?php ActiveForm::end(); ?>

views/interview/feedback.php
<?php
/* @var $this yii\web\View */
?>
<?php echo $this->render('forms/feedback', [
    'model' => $model,
]); ?>

views/interview/interview-complete.php
<?php
use kartik\widgets\ActiveForm;
use yii\tagsinput\TagsInput;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\web\JsExpression;

/** @var app\models\Interview $model */
$form = ActiveForm::begin([
    'action' => Url::to('/interview/interview-complete'),
    'id' => $model->formName(),
    'enableClientValidation' => false,
    'options' => [
        'class' => 'clearfix',
    ]
]); ?>
<?= Html::activeHiddenInput($model, 'candidate_id'); ?>
<?= Html::activeHiddenInput($model, 'interview_id'); ?>
<?= $form->field($model, 'participants')->widget(TagsInput::className(), [
    'clientOptions' => [
        'typeaheadjs' => [
            'displayKey' => 'full_name',
            'valueKey' => 'full_name',
            'source' => new JsExpression('(function () {
                var users = new Bloodhound({
                    datumTokenizer: Bloodhound.tokenizers.obj.whitespace(\'full_name\'),
                    queryTokenizer: Bloodhound.tokenizers.whitespace,
                    remote: {
                        url: \'/user/list?term=%QUERY\',
                        filter: function (list) {
                            return $.map(list.data, function (user) {
                                return user;
                            });
                        }
                    }
                });
                users.initialize();
                return users.ttAdapter();
            })()'),
        ],
    ]
]); ?>

<?= $form->field($model, 'content')->textarea(['rows' => 4]); ?>

<?php ActiveForm::end(); ?>

<blockquote>
    <small>Just use placeholder <strong><em>#link</em></strong> for place feedback form's link, or raw text <?= Url::to(['interview/feedback', 'id' => $model->interview_id], true); ?></small>
</blockquote>

views/interview/send-notification.php
<?php
use kartik\widgets\ActiveForm;
use yii\tagsinput\TagsInput;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\web\JsExpression;

/** @var app\models\Interview $model */
$form = ActiveForm::begin([
    'action' => Url::to('/interview/send-notification'),
    'id' => $model->formName(),
    'enableClientValidation' => false,
    'options' => [
        'class' => 'clearfix',
    ]
]); ?>
<?= Html::activeHiddenInput($model, 'candidate_id'); ?>
<?= $form->field($model, 'participants')->widget(TagsInput::className(), [
    'clientOptions' => [
        'typeaheadjs' => [
            'displayKey' => 'full_name',
            'valueKey' => 'full_name',
            'source' => new JsExpression('(function () {
                var users = new Bloodhound({
                    datumTokenizer: Bloodhound.tokenizers.obj.whitespace(\'full_name\'),
                    queryTokenizer: Bloodhound.tokenizers.whitespace,
                    remote: {
                        url: \'/user/list?term=%QUERY\',
                        filter: function (list) {
                            return $.map(list.data, function (user) {
                                return user;
                            });
                        }
                    }
                });
                users.initialize();
                return users.ttAdapter();
            })()'),
        ],
    ]
]); ?>

<?= $form->field($model, 'comment')->textarea(['rows' => 3]); ?>
<?= Html::activeCheckbox($model, 'attach_cv'); ?>

<?php ActiveForm::end(); ?>